services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:9930779-alpine
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=CHANGEME
      - LAVALINK_SERVER_SOURCES_LOCAL=true
    volumes:
      - ./data/cache/:/opt/Lavalink/cache/
  app:
    build: .
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    init: true
